### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by MohamedAl-Kainai**
This will fix this error
```
Exception: type '_OneByteString' is not a subtype of type 'AddressLabel' in type cast 
       at new Address.fromJson(address.dart:84)
       at new Contact.fromJson.<fn>(contact.dart:175)
       at SetMixin.toList(dart:collection)
       at new Contact.fromJson(contact.dart:176)
       at FlutterContacts._select.<fn>(flutter_contacts.dart:329)
       at SetMixin.toList(dart:collection)
       at FlutterContacts._select(flutter_contacts.dart:330)
```

### CODE REVIEW

**Comment by yassinsameh** [comment]
Could you please provide an example of how to reproduce this error with the current package code?  @MohamedAl-Kainai

**Comment by saropa** [comment]
The current code ```'' as AddressLabel``` doesn't look great, but suggestion defaulting to ```AddressLabel.home``` makes an incorrect assumption.

**Comment by MohamedAl-Kainai** [comment]
Instead of AddressLabel.home just return null that will be better.

**Comment by MohamedAl-Kainai** [comment]
I think it will be the best solution 👍

**Comment by joachim-quis** [comment]
Thanks for the fix @MohamedAl-Kainai !!
Regarding 'other' vs 'home', actually the default is 'home' in other places too, so I think 'home' is fine.

**Pull request merged**
